# Generated by Django 5.0.1 on 2025-09-21 15:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice_collections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('api_request', 'API Request'), ('payment_processed', 'Payment Processed'), ('webhook_received', 'Webhook Received'), ('notification_sent', 'Notification Sent'), ('status_changed', 'Status Changed'), ('error_occurred', 'Error Occurred'), ('user_action', 'User Action'), ('system_action', 'System Action')], db_index=True, max_length=50)),
                ('action_description', models.CharField(max_length=255)),
                ('invoice_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('payment_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('actor_type', models.CharField(default='system', max_length=20)),
                ('actor_id', models.CharField(blank=True, max_length=100)),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type', 'created_at'], name='audit_logs_action__94af82_idx'), models.Index(fields=['invoice_id', 'created_at'], name='audit_logs_invoice_0fae3f_idx'), models.Index(fields=['payment_id', 'created_at'], name='audit_logs_payment_3e1937_idx'), models.Index(fields=['actor_type', 'created_at'], name='audit_logs_actor_t_b4d6a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExternalSystemIntegration',
            fields=[
                ('integration_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_type', models.CharField(choices=[('salesforce', 'Salesforce'), ('stripe', 'Stripe'), ('slack', 'Slack'), ('email', 'Email')], db_index=True, max_length=20)),
                ('system_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('maintenance', 'Maintenance')], db_index=True, default='active', max_length=20)),
                ('base_url', models.URLField()),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('health_check_status', models.CharField(blank=True, max_length=20)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('requests_per_minute', models.PositiveIntegerField(default=60)),
                ('requests_per_hour', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'external_system_integrations',
                'ordering': ['system_type', 'system_name'],
                'indexes': [models.Index(fields=['system_type', 'status'], name='external_sy_system__b12068_idx'), models.Index(fields=['status', 'last_health_check'], name='external_sy_status_dff903_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('stripe', 'Stripe'), ('salesforce', 'Salesforce'), ('internal', 'Internal System')], db_index=True, max_length=20)),
                ('event_type', models.CharField(choices=[('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed'), ('invoice_updated', 'Invoice Updated'), ('collection_request', 'Collection Request'), ('status_update', 'Status Update'), ('error_notification', 'Error Notification')], db_index=True, max_length=50)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], db_index=True, default='received', max_length=20)),
                ('payload', models.JSONField()),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('processing_error', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'webhook_events',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['source', 'event_type', 'received_at'], name='webhook_eve_source_6fd0e8_idx'), models.Index(fields=['status', 'next_retry_at'], name='webhook_eve_status_7239e7_idx'), models.Index(fields=['external_id'], name='webhook_eve_externa_c34803_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalesforceNotification',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed'), ('collection_initiated', 'Collection Initiated'), ('status_update', 'Status Update'), ('error_occurred', 'Error Occurred')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('acknowledged', 'Acknowledged')], db_index=True, default='pending', max_length=20)),
                ('sf_webhook_url', models.URLField()),
                ('sf_webhook_secret', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField()),
                ('delivery_attempts', models.PositiveIntegerField(default=0)),
                ('max_delivery_attempts', models.PositiveIntegerField(default=3)),
                ('last_delivery_error', models.TextField(blank=True)),
                ('response_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesforce_notifications', to='invoice_collections.invoice')),
            ],
            options={
                'db_table': 'salesforce_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invoice', 'created_at'], name='salesforce__invoice_14480c_idx'), models.Index(fields=['status', 'next_retry_at'], name='salesforce__status_8445b6_idx'), models.Index(fields=['notification_type', 'created_at'], name='salesforce__notific_8bff68_idx')],
            },
        ),
    ]
