# Generated by Django 5.0.1 on 2025-09-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_collections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='sf_invoice_id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='external_invoice_id',
            field=models.CharField(db_index=True, default='', max_length=100, unique=True),
        ),
    ]
