# Generated by Django 5.0.1 on 2025-09-21 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_processing', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymentwebhook',
            new_name='payment_pro_stripe__bbfd25_idx',
            old_name='payment_web_stripe__23d0fa_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentwebhook',
            new_name='payment_pro_webhook_d755ac_idx',
            old_name='payment_web_webhook_5c6383_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentwebhook',
            new_name='payment_pro_process_e4bd0b_idx',
            old_name='payment_web_process_ee3d53_idx',
        ),
        migrations.AlterModelTable(
            name='paymentwebhook',
            table='payment_processing_webhooks',
        ),
    ]
