# Generated by Django 5.0.1 on 2025-09-21 18:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A2AAgent',
            fields=[
                ('agent_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=100, unique=True)),
                ('agent_type', models.CharField(choices=[('collections_agent', 'Collections Agent'), ('payment_agent', 'Payment Agent'), ('customer_support_agent', 'Customer Support Agent'), ('fraud_detection_agent', 'Fraud Detection Agent'), ('reconciliation_agent', 'Reconciliation Agent')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('a2a_endpoint', models.URLField()),
                ('public_key', models.TextField()),
                ('capabilities', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('error', 'Error')], default='active', max_length=20)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'a2a_agents',
                'ordering': ['agent_name'],
                'indexes': [models.Index(fields=['agent_type', 'status'], name='a2a_agents_agent_t_c6b0d7_idx'), models.Index(fields=['status', 'last_heartbeat'], name='a2a_agents_status_8d96aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='A2AConversation',
            fields=[
                ('conversation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_type', models.CharField(choices=[('payment_initiation', 'Payment Initiation'), ('customer_verification', 'Customer Verification'), ('fraud_check', 'Fraud Check'), ('reconciliation', 'Reconciliation'), ('mandate_verification', 'Mandate Verification')], max_length=30)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='initiated', max_length=20)),
                ('context_data', models.JSONField(default=dict)),
                ('authorization_token', models.CharField(blank=True, max_length=255)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('initiator_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_conversations', to='a2a_broker.a2aagent')),
                ('target_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_conversations', to='a2a_broker.a2aagent')),
            ],
            options={
                'db_table': 'a2a_conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='A2AMessage',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('request', 'Request'), ('response', 'Response'), ('notification', 'Notification'), ('error', 'Error')], max_length=20)),
                ('payload', models.JSONField()),
                ('signature', models.CharField(max_length=512)),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='a2a_broker.a2aconversation')),
                ('sender_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a2a_broker.a2aagent')),
            ],
            options={
                'db_table': 'a2a_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='A2AAuthorization',
            fields=[
                ('authorization_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_type', models.CharField(choices=[('payment_initiate', 'Payment Initiation'), ('customer_data_access', 'Customer Data Access'), ('mandate_verification', 'Mandate Verification'), ('fraud_check', 'Fraud Check'), ('reconciliation', 'Reconciliation')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=20)),
                ('scope_data', models.JSONField(default=dict)),
                ('max_amount_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('max_frequency_per_hour', models.PositiveIntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('grantee_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_authorizations', to='a2a_broker.a2aagent')),
                ('grantor_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_authorizations', to='a2a_broker.a2aagent')),
            ],
            options={
                'db_table': 'a2a_authorizations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['grantor_agent', 'status'], name='a2a_authori_grantor_0e257c_idx'), models.Index(fields=['grantee_agent', 'status'], name='a2a_authori_grantee_8d64f2_idx'), models.Index(fields=['permission_type', 'status'], name='a2a_authori_permiss_778f3a_idx'), models.Index(fields=['status', 'expires_at'], name='a2a_authori_status_a2e06b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='a2aconversation',
            index=models.Index(fields=['initiator_agent', 'status'], name='a2a_convers_initiat_bb54c6_idx'),
        ),
        migrations.AddIndex(
            model_name='a2aconversation',
            index=models.Index(fields=['target_agent', 'status'], name='a2a_convers_target__63fde3_idx'),
        ),
        migrations.AddIndex(
            model_name='a2aconversation',
            index=models.Index(fields=['conversation_type', 'status'], name='a2a_convers_convers_67aa1d_idx'),
        ),
        migrations.AddIndex(
            model_name='a2aconversation',
            index=models.Index(fields=['status', 'expires_at'], name='a2a_convers_status_76394a_idx'),
        ),
        migrations.AddIndex(
            model_name='a2amessage',
            index=models.Index(fields=['conversation', 'created_at'], name='a2a_message_convers_3a7370_idx'),
        ),
        migrations.AddIndex(
            model_name='a2amessage',
            index=models.Index(fields=['sender_agent', 'created_at'], name='a2a_message_sender__305b53_idx'),
        ),
        migrations.AddIndex(
            model_name='a2amessage',
            index=models.Index(fields=['message_type', 'created_at'], name='a2a_message_message_8eaa6a_idx'),
        ),
    ]
